# Generated by Django 5.1.7 on 2025-03-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_whois_information", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipinfo",
            name="address_information",
        ),
        migrations.RemoveField(
            model_name="ipinfo",
            name="cidr_block",
        ),
        migrations.AddField(
            model_name="ipinfo",
            name="end_ip",
            field=models.GenericIPAddressField(),
        ),
        migrations.AddField(
            model_name="ipinfo",
            name="start_ip",
            field=models.GenericIPAddressField(),
        ),
    ]
